symfony:
	docker exec -t among-us-php composer require symfony
skeleton:
	docker exec -t among-us-php composer create-project symfony/website-skeleton among-us-irl
install:
	docker exec -t among-us-php npm install
	docker exec -t among-us-php composer install