version: '3.7'

networks:
  webapp:
    external: false
    name: ${CONTAINER_NAME_PREFIX}-webapp

services:
  app-web:
    image: ${APP_WEB_IMAGE}
    container_name: ${CONTAINER_NAME_PREFIX}-web
    networks:
      - webapp
    depends_on:
      - app-php
    links:
      - app-php:php
    volumes:
      - ./application:/var/www/html
      - ./config/web/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/web/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  app-php:
    image: ${APP_PHP_IMAGE}
    container_name: ${CONTAINER_NAME_PREFIX}-php
    labels:
      - traefik.enable=false
    networks:
      - webapp
    depends_on:
      - app-db
    links:
      - app-db:db
    volumes:
      - ./application:/var/www/html/

  app-adminer:
    container_name: ${CONTAINER_NAME_PREFIX}-adminer
    image: ${APP_ADMINER_IMAGE}
    restart: always
    links:
      - app-db:db
    networks:
      - webapp
    depends_on:
      - app-db
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}"

  app-db:
    image: ${APP_DB_IMAGE}
    container_name: ${CONTAINER_NAME_PREFIX}-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "--encoding=${DB_CHARSET}"
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: "Europe/Prague"
    networks:
      - webapp
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${DB_HOST_PORT}:5432"

volumes:
  postgres:
